CREATE TABLE IF NOT EXISTS users
(
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(30) NOT NULL,
    email   VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS item_requests
(
    item_request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description     VARCHAR(1000)               NOT NULL,
    requester_id    BIGINT REFERENCES users (user_id) ON DELETE CASCADE,
    created_time    TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS items
(
    item_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(75)  NOT NULL,
    description  VARCHAR(255) NOT NULL,
    is_available BOOLEAN      NOT NULL,
    owner_id     BIGINT       REFERENCES users (user_id) ON DELETE SET NULL,
    request_id   BIGINT       REFERENCES item_requests (item_request_id)
);

CREATE TABLE IF NOT EXISTS bookings
(
    booking_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    end_time   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    item_id    BIGINT                      REFERENCES items (item_id) ON DELETE SET NULL,
    user_id    BIGINT                      REFERENCES users (user_id) ON DELETE SET NULL,
    status     VARCHAR(20)                 NOT NULL
);

CREATE TABLE IF NOT EXISTS comments
(
    comment_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text         VARCHAR(512)                NOT NULL,
    item_id      BIGINT REFERENCES items (item_id) ON DELETE CASCADE,
    author_id    BIGINT REFERENCES users (user_id) ON DELETE CASCADE,
    created_time TIMESTAMP WITHOUT TIME ZONE NOT NULL
);